---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/posts":
    get:
      summary: Retrieves all posts
      responses:
        '200':
          description: posts found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
